server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:lavagedb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwtSecret: lavagesystemSecretKeyWithAtLeast256BitsForHS256Algorithm2026Security
  jwtExpirationMs: 86400000 # 24 heures
